### ISSUE TITLE
Calendar:emit() can be refactored.

### ISSUE THREAD

**Issue by diasbruno** [evangilo/datepicker#1]
This `emit` dispatcher can be simplified to just know what it need (there are a lot of filters [line 38](https://github.com/evangilo/datepicker/blob/master/src/scripts/calendar.js#L38)).

**Comment by diasbruno** [comment]
This was already improved. Closing it.

**Comment by evangilo** [comment]
https://github.com/evangilo/light-datepicker/pull/11
